### ISSUE TITLE
Compatible with the latest version of ROOT 6.13.02?

### ISSUE THREAD

**Issue by beckstev** [nmohr/pyxar#2]
Is the latest version of _pyxar_ ( <https://github.com/simonspa/pyxar> ) compatible with the newest version of _ROOT 6.13.02_?

When I want to run 
```
./pyXar
```
I get the following error:
```python
Traceback (most recent call last):
  File "./pyXar", line 7, in <module>
    import ROOT
  File "/home/sb/Dokumente/root_folder/build/lib/ROOT.py", line 24, in <module>
    import cppyy
  File "/home/sb/Dokumente/root_folder/build/lib/cppyy.py", line 61, in <module>
    import libPyROOT as _backend
ImportError: dynamic module does not define init function (initlibPyROOT)
```
Do you guys have maybe a idea how to solve this problem?

Best regards 

Steven

**Comment by beckstev** [comment]
**UPDATE**

I solved the problem of

```
./pyXar 
```
by changing
```
#!/usr/bin/python
```
to
```
#!/usr/bin/env python
```
However I am not sure if pyxar works with ROOT 6.13.02.

Thanks.

Best regards 

Steven
